language: cpp
compiler:
  - gcc
before_install: 
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y --force-yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq gcc-4.8
  - sudo apt-get install -qq g++-4.8
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20
  - sudo update-alternatives --config gcc
  - sudo update-alternatives --config g++
  - sudo apt-get install libpcap-dev
script: make

